CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_username VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    target_user_id BIGINT,
    details VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_admin_audit_log_created_at ON admin_audit_log (created_at DESC);